### PR TITLE
UI & project updates

### PR DESCRIPTION
**Pull request by kremalicious**
All new UI and data flow, and various project updates:

- setup CI, running build & lint
- cleanup env vars
- simplify eslint setup by using default Next.js setup
- remove a bunch of committed `node_modules`
- use default Next.js tsconfig
- updated readme

Current status, thanks @jamiehewitt15 & @mihaisc, that was nice to work with so far.

(Light/Dark mode switching is just delegated to your OS settings to keep it simple)

Screen Shot 2022-10-18 at 21 51 38

Screen Shot 2022-10-18 at 21 52 19

### CODE REVIEW

**Comment by mihaisc** [comment]
api updated

**Comment by kremalicious** [comment]
actually works now, as before we only fetched on a per-network basis. Removed pretty much all of the data restructuring code and now doing this:

- get data from API
- restructure everything into an object with network names as keys and return this
- then just iterate over this one `data` object on our index page and be done with it

This seemed to be the most fitting data structure for this new layout:

Screen Shot 2022-10-18 at 18 20 11

Some things could be done over on the API to reduce some more filters, like instead of:

```
market: "UP"
```

it should return the same data structure as everywhere else:

```
market: { status: "UP" }
```

And would also help putting all our components under a `components` array, as otherwise have to filter for the other keys which are not the components

**Comment by mihaisc** [comment]
`market: { status: "UP" }`  will do.

> And would also help putting all our components under a components array,

Don't get it, give an example please

**Comment by kremalicious** [comment]
Currently getting this for each network:

```js
{
  __v: 0
  _id: "634f0466c118361aa402c4eb"
  aquarius: { status: "UP", response: 200, validChainList: true, … }
  currentBlock: 15777209
  dataFarming: "UP"
  lastUpdatedOn: 1666122853569
  market: "UP"
  network: "mainnet"
  operator: { status: "UP", response: 200, version: "1.0.1", … }
  provider: { status: "UP", response: 200, version: "1.3.4", … }
  subgraph: { status: "UP", response: 200, version: "2.1.3", … }
}
```

And this would be easier to differentiate which data is for components:

```js
{
  __v: 0
  _id: "634f0466c118361aa402c4eb"
  currentBlock: 15777209
  lastUpdatedOn: 1666122853569
  network: "mainnet"
  components: {
    market: "UP"
    dataFarming: "UP"
    aquarius: { status: "UP", response: 200, validChainList: true, … }
    operator: { status: "UP", response: 200, version: "1.0.1", … }
    provider: { status: "UP", response: 200, version: "1.3.4", … }
    subgraph: { status: "UP", response: 200, version: "2.1.3", … }
  }
}
```

**Comment by mihaisc** [comment]
Sure, will do

**Comment by mihaisc** [comment]
> And as seen on screenshot, for the subgraph the status doesn't change to WARNING if there's a statusMessages, but it probably should.

 That was an intentional change. By common standard `WARNING` would be too much for just a version mismatch. People would get the wrong impression. Considering a lot of the times we don't upgrade intentionally.

**Comment by kremalicious** [comment]
cool, thanks. On first look, `dataFarming` and `market` here not under `components` key, was this intended?

**Comment by mihaisc** [comment]
Yes, but don't know why... it was late 😆

**Comment by kremalicious** [comment]
all good now with data structure. Now checking correctness of data. This here seems weird:

Screen Shot 2022-10-19 at 12 44 07

So there are 3 different versions in the data:

- `latestRelease`
- `monitorVersion`
- `version`

Where I assumed `version` is the deployed version. But based on. screenshot it seems to be not?

**Comment by mihaisc** [comment]
Aquarius has 2 components, (this is why i was adding the name in the message). It's the aquarius api and aquarius event monitoring. There is only one api for all networks and it is represented by `version` . On each network we have an aquarius event monitor deployed that is indexing stuff. This is represented here by `monitorVersion` . I'll add the component back in the message name for aquarius event monitor.

**Comment by mihaisc** [comment]
I forgot to fix the faucet status

**Comment by kremalicious** [comment]
and getting double event-monitor with different version numbers for each network:

Screen Shot 2022-10-19 at 16 45 13

**Comment by kremalicious** [comment]
> I forgot to fix the faucet status, to show Warning instead of Down

I'm undecided by now as I can see how this actually makes sense visually:
Screen Shot 2022-10-19 at 16 50 32

Like, subgraph in a way can be used when not fully synced. So maybe makes sense having a bit of different rules per component, and if it is indeed unusable it gets the `DOWN` status, just like we have now on faucet

**Comment by kremalicious** [comment]
think my confusion also came from fact that we mix up specific status & severity, where we should only use severity as `status`. So not "Up" & "Down", but `success`, `error`, `warning`.

**Comment by mihaisc** [comment]
Should we have an url for the relevant components? So you can quickly navigate to that component from the status page?

**Comment by kremalicious** [comment]
yeah was thinking about linking the component titles to something, like GitHub repo, which Could simply construct from the component name. But the actual url we are testing would be more useful, then I would need this pushed by API so as new `url` key would be perfect

**Comment by mihaisc** [comment]
Will do so next release will have: 
- `url`
- improved messages for faucet for example : `Low on OCEAN. {ocean} remaining. ` (Warning) ,  or `Less than 1000 OCEAN remaining` (error) 
- fix provider name  (now is `event-monitor`)
- insipred by github, change status to one of the following
     a) Normal, Degraded, Outage 
     b) Operational, Partial Outage, Major Outage

**Comment by mihaisc** [comment]
Wait, you mean repo url?  I meant deployment url like www.market.oceanprotocol.com , not https://github.com/oceanprotocol/market

**Comment by mihaisc** [comment]
Should be good to go. Do you have any more changes planned?

**Comment by kremalicious** [comment]
dropped in [swr](https://swr.vercel.app) so now we get among other things:
- refetch upon window focus
- refetch upon becoming online (after being offline)
- refetch after 60 seconds

**Comment by mihaisc** [comment]
Really nice that netlify provides a quick qr code to test on mobile
image

**Review by mihaisc — APPROVED** [review]

**Pull request merged**
